// Variables
let nombre = document.querySelector("#nombre")
let nombreClase = document.querySelector(".nombre")
let apellido = document.querySelector("#apellido")
let correo = document.querySelector("#correo")
let cantidad = document.querySelector("#cantidad")
let categoria = document.querySelector("#categoria")
let totalPagar = document.querySelector("#totalPagar")
const def = document.querySelector("#default")
const form = document.querySelector("#form")
const cards = document.querySelector("#cards")
const campos = document.querySelector("#campos")
const borrar = document.querySelector("#borrar")
const resumen = document.querySelector("#resumen")
const valorTicket = document.querySelector("#valorTicket")